FROM ubuntu:latest

CMD echo "Hello, world!"

#FROM mcr.microsoft.com/windows/nanoserver:1809

#SHELL ["powershell", "-Command","$ErrorActionPreference = 'Stop'; $Progresspreference = 'SilentlyContinue';"]

#RUN Write-Host 'Hello World!'

#CMD echo Hello, world!
